Parse one character country code for Germany.
BorderTech/mrz-java pull request #3
Opened 2020-10-20 11:47 UTC by UKreher

Germany does not use a 3-character-code but just one character.
See https://en.wikipedia.org/wiki/Machine-readable_passport#Nationality_codes_and_checksum_calculation
This prevents the MRZ from corresponding documents to be found.

2020-10-25 23:05 UTC, marksreeves commented
@jonathanaustin PTAL & merge if OK

2020-10-26 01:09 UTC, jonathanaustin requested changes
Thanks for the change. As per other comment, could you please add a unit test for the German Country code.

2020-10-26 01:09 UTC, jonathanaustin commented on src/main/java/com/innovatrics/mrz/MrzFinderUtil.java
> +	private static final Pattern MRZFIRSTLINE = Pattern.compile("[P|V|A|C|I][A-Z0-9<]([A-Z]{3}|D<<)[A-Z0-9<]{25,39}");
This change looks good. Could you please add a Unit test for this scenario. Thanks.

2020-10-27 00:01 UTC, jonathanaustin commented on src/test/java/com/innovatrics/mrz/MrzFinderUtilTest.java
> +  private static final String INVALID_GER_MRZ = "P<DE<MUSTERMANN<<ERIKA<<<<<<<<<<<<<<<<<<<<<<\nC01X00T478D<<6408125F2702283<<<<<<<<<<<<<<<4";
@UKreher The unit tests look good. What might help with testing the "invalid" MRZ is making the MRZ invalid on the second line. As the regexp to identify the first line is very specific the Util tends to return a not found when the characters are invalid on the first line. Hope that helps.
It might still be a good idea to add a test for an invalid MRZ on the first line but it will need to pass that first line regexp and then fail the parsing. Let me know what you think.

2020-10-27 08:04 UTC, UKreher commented
Oops. Actually, the tests did not look good. The usual copy thing … Sorry.

Since a failing second line is already part of the test, I focused on testing the first line where the regexp changed – but expected the wrong exception. Feel free to change this or add additional tests.

2020-10-27 23:44 UTC, jonathanaustin approved these changes
Change and tests look good. Thanks. We will merge and release a new version.

2020-10-27 23:45 UTC, merged